### ISSUE TITLE
Portfolio using Bootstrap

### ISSUE THREAD

**Issue by faisalakb** [MesakDuduCoder/Bootstrap-microverse#2]
Your design is good. Please check the color contrast ratio. For help you may use [Link](https://www.aditus.io/button-contrast-checker/)

**Comment by massazoum** [comment]
please make sure to use padding on the card section for the desktop version.

**Comment by arnoldnekemiah** [comment]
> Your design is good. Please check the color contrast ratio. For help you may use [Link](https://www.aditus.io/button-contrast-checker/)

Thank You for the suggestion, will try to implement it

**Comment by arnoldnekemiah** [comment]
> please make sure to use padding on the card section for the desktop version.

Noted, Thank you
