### ISSUE TITLE
Peer-to-peer feedback

### ISSUE THREAD

**Issue by yin-ka** [MesakDuduCoder/Bootstrap-microverse#3]
- You have done a good job. However, there is room for improvement.
- You need to upgrade your readme file to make your work look more professional.
- Kindly make use of comments to aid the navigation of your codes.

**Comment by MesakDuduCoder** [comment]
> * You have done a good job. However, there is room for improvement.
> * You need to upgrade your readme file to make your work look more professional.
> * Kindly make use of comments to aid the navigation of your codes.

**Comment by MesakDuduCoder** [comment]
Yes I will look into it
